on: [push, pull_request]
name: Build
env:
  CGO_ENABLED: "0"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, windows-2022, macos-12, macos-13, macos-14]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: go build