on: [push, pull_request]
name: Unit Tests
jobs:
  test_manifest_package:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test Manifest
      run: go test
      working-directory: manifest
    - name: Test Game Updates
      run: go test
      working-directory: gameupdates